---
title: "Stat 147 Assignment 4"
author:
- name: Marc Shervin Ignacio
  affiliation: "2019-04690"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  html_document:
    theme: lumen
    toc: yes
    toc_float: yes
    toc_depth: 4
    number_sections: no
    highlight: pygments
    fig_caption: yes
    code_folding: show
editor_options:
  markdown:
    wrap: 72
---
```{r, echo=FALSE}
show_table <- function(x,text=NULL){
  x %>%
  kbl(caption=text) %>%
  kable_classic(full_width = F, html_font = "Cambria")
}
```

```{r setup, warning=FALSE,message=FALSE}
library(factoextra)
library(knitr)
library(kableExtra)
library(ggplot2)
library("ggrepel")
library(dplyr)
```

```{r}
nba <- readxl::read_xlsx('NBA 1819 Regular Season - Data.xlsx')

show_table(head(nba),"NBA 1819 Regular Season Data")
```
### Knowing more about our dataset:
```{r}
str(nba)
```

```{r}
summary(nba)
```
### Preparing our data
```{r}
colnames(nba)
```

```{r}
nba_shooting <- nba[9:17]
show_table(head(nba_shooting), "Shooting statistics")

nba_nonshooting <- nba[18:ncol(nba)]
show_table(head(nba_nonshooting), "Shooting statistics")
```




### Principal Component Analysis

#### Shooting Statistics
```{r}
pca_shooting <- prcomp(x = nba_shooting, scale.=T)
show_table(summary(pca_shooting)$importance, "Proportion of Total Variance retained per PC")
show_table(cbind(1:length(pca_shooting$sdev),pca_shooting$sdev),"Standard deviation of components")
show_table(pca_shooting$rotation, "PC Loadings")
```

#### Non-shooting Statistics
```{r}
pca_nonshooting <- prcomp(x = nba_nonshooting, scale.=T)
show_table(summary(pca_nonshooting)$importance, "Proportion of Total Variance retained per PC")
show_table(cbind(1:length(pca_nonshooting$sdev),pca_nonshooting$sdev),"Standard deviation of components")
show_table(pca_nonshooting$rotation, "PC Loadings")

```

```{r}
data_with_scores <- nba %>%
                      dplyr::mutate(shooting1 = pca_shooting$x[,1],
                             shooting2 = pca_shooting$x[,2],
                             others1 = pca_nonshooting$x[,1],
                             others2 = pca_nonshooting$x[,2])
data_with_scores %>% show_table()
```
```{r}
#PCA_Shooting
arrange(data_with_scores, desc(shooting1))[1:5,c("PLAYER","shooting1")] %>% show_table("Top 5 for Shooting1")
arrange(data_with_scores, (shooting1))[1:5,c("PLAYER","shooting1")] %>% show_table("Last 5 for Shooting1")

arrange(data_with_scores, desc(shooting2))[1:5,c("PLAYER","shooting2")] %>% show_table("Top 5 for Shooting2")
arrange(data_with_scores, (shooting2))[1:5,c("PLAYER","shooting2")] %>% show_table("Last 5 for Shooting2")
```
```{r}
#PCA_Nonhooting
arrange(data_with_scores, desc(others1))[1:5,c("PLAYER","others1")] %>% show_table("Top 5 for others1")
arrange(data_with_scores, (others1))[1:5,c("PLAYER","others1")] %>% show_table("Last 5 for others1")

arrange(data_with_scores, desc(others2))[1:5,c("PLAYER","others2")] %>% show_table("Top 5 for others2")
arrange(data_with_scores, (others2))[1:5,c("PLAYER","others2")] %>% show_table("Last 5 for others2")
```


### Visualization of results
```{r}
factoextra::fviz_pca_var(pca_shooting)
layout(matrix(1:2, ncol=2))
screeplot(pca_shooting)
screeplot(pca_shooting, type="lines")

```

```{r}
factoextra::fviz_pca_var(pca_nonshooting)
layout(matrix(1:2, ncol=2))
screeplot(pca_nonshooting)
screeplot(pca_nonshooting, type="lines")
```


```{r}
data_with_scores %>%
  filter(center + forward + guard == 1) %>%
  group_by(POSITION) %>%
  summarise(shooting1 = median(shooting1),
            shooting2 = median(shooting2),
            others1 = median(others1),
            others2 = median(others2)) %>%
  ungroup() %>%
  tidyr::pivot_longer(cols = shooting1:others2, names_to = "PCs", values_to = "score") %>%
  ggplot(aes(x = PCs, y = score)) +
    geom_bar(aes(fill = POSITION), position = "dodge", stat = "identity") +
    ggthemes::theme_gdocs()
```

```{r}
#MEAN BY POSITION
data_with_scores %>%
  filter(center + forward + guard == 1) %>%
  group_by(POSITION) %>%
  summarise(across(everything(), mean)) %>%
  select(9:17) %>%
  show_table("Mean across shooting statistics")

data_with_scores %>%
  filter(center + forward + guard == 1) %>%
  group_by(POSITION) %>%
  summarise(across(everything(), mean)) %>%
  select(18:ncol(nba)) %>%
  show_table("Mean across nonshooting statistics")
```



```{r}
center1 <- data_with_scores %>% select(shooting1, shooting2)
mahal1 <- mahalanobis(x = center1, center = cbind(c(0,0)), cov = var(center1))
center2 <- data_with_scores %>% select(others1, others2)
mahal2 <- mahalanobis(x = center2, center = cbind(c(0,0)), cov = var(center2))
```

```{r}
data_with_scores %>%
  mutate(
    outlier = (mahal1 > 9) & (shooting1 < 0) & (shooting2 > 0) & center,
    label   = if_else(outlier, PLAYER, "")
  ) %>%
  ggplot(aes(x = shooting1, y = shooting2)) +
  geom_hline(yintercept = 0, col = "black") +
  geom_vline(xintercept = 0, col = "black") +
  geom_point(aes(col = center)) +
  geom_text_repel(aes(label = label), max.overlaps = 20, size = 3) +
  scale_color_manual(values = c("gray80", "firebrick"))
```

```{r}
data_with_scores %>%
  mutate(
    extreme = (mahal2 > 9) & (others1 < 0) & (others2 < 0) & center,
    label   = if_else(extreme, PLAYER, "")
  ) %>%
  ggplot(aes(x = others1, y = others2)) +
  geom_hline(yintercept = 0, col = "black") +
  geom_vline(xintercept = 0, col = "black") +
  geom_point(aes(col = center)) +
  geom_text_repel(aes(label = label), max.overlaps = 20, size = 3) +
  scale_color_manual(values = c("gray80", "firebrick"))
```

