---
title: "Stat 147 Assignment 5"
author:
- name: Marc Shervin Ignacio
  affiliation: "2019-04690"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  word_document:
    toc: yes
    toc_depth: '4'
  html_document:
    theme: lumen
    toc: yes
    toc_float: yes
    toc_depth: 4
    number_sections: no
    highlight: pygments
    fig_caption: yes
    code_folding: show
editor_options:
  markdown:
    wrap: 72
---
```{r, warning=FALSE,message=FALSE}
library(psych)
library("GPArotation")
library("readxl")
library(knitr)
library(kableExtra)
library(ggplot2)
```

```{r, echo=FALSE}
show_table <- function(x,text=NULL){
  x %>%
  kbl(caption=text) %>%
  kable_classic(full_width = F, html_font = "Cambria")
}
```


```{r}
setwd("C:/Users/marci/Desktop/stat-147-workspace/Assignment 5")
vitamin <- read_xlsx("vitamins example data.xlsx")[,c(-12,-14,-16)]
vitamin %>%
  head %>%
  show_table("Dataset")
```

### Tests for adequacy
Kaiser-Meyer-Olkin Measure of Sampling Adequacy
```{r}
psych::KMO(r = vitamin)
```

Test for Sphericity
```{r}
psych::cortest.bartlett(R = cor(vitamin), n = 300)
```

```{r, echo=FALSE, collapse=TRUE}
code_category <- function(x){
  dplyr::case_when(x == "p1" ~ "increases body resistance",
            x == "p2" ~ "makes body strong and healthy",
            x == "p3" ~ " provides extra energy/strength",
            x == "p4" ~ "enhances/increasesappetite",
            x == "p5" ~ "sharpens memory/enhances mental alertness",
            x == "p6" ~ "has no side effects",
            x == "p7" ~ "promotes weight gain",
            x == "p8" ~ "revitalizes/conditions body",
            x == "p9" ~ "relieves tiredness/fatigue/stress",
            x == "p10" ~ "has complete vitamins and minerals",
            x == "p11" ~ "fights lack of sleep",
            x == "p13" ~ "promotes healthy hair",
            x == "p15" ~ "promotes growth/height",
            x == "p17" ~ "makes bones/teeth strong",
            x == "p18" ~ "promotes better blood circulation",
            x == "p19" ~ "promotes good skin",
            x == "p20" ~ "promotes good eyesight",
            x == "p21" ~ " makes one feel younger/revitalized",
            x == "p22" ~ "extends peak hours",
            x == "p23" ~ "keeps one full of energy",
            TRUE ~ "NA")
  }
```
### EFA Section


```{r}
library(nFactors)
ev <- eigen(cor(vitamin)) # get eigenvalues
ap <- parallel(subject=nrow(vitamin),var=ncol(vitamin),
  rep=100,cent=.05)
nS <- nScree(x=ev$values, aparallel=ap$eigen$qevpea)
plotnScree(nS)
```

#### 4 FACTORS
```{r}
fa_4varimax <- psych::fa(r = vitamin,
nfactors = 4,
rotate = "varimax",
scores = "regression",
SMC = T,
fm = "pa")

fa_4quartimax <- psych::fa(r = vitamin,
nfactors = 4,
rotate = "quartimax",
scores = "regression",
SMC = T,
fm = "pa")

fa_4oblimin <- psych::fa(r = vitamin,
nfactors = 4,
rotate = "oblimin",
scores = "regression",
SMC = T,
fm = "pa")

```

```{r}
fa.diagram(fa_4varimax)
fa.diagram(fa_4quartimax)
fa.diagram(fa_4oblimin)
```
```{r}
fa.sort(fa_4varimax$loadings)
```
```{r,echo=FALSE,collapse=TRUE}
fa_4varimax_sorted <- fa.sort(fa_4varimax$loadings) 
loading_matrix <- as.data.frame((matrix(fa_4varimax_sorted, ncol = 4, nrow = 20, 
                         dimnames = list(NULL,colnames(fa_4varimax_sorted)))))
loading_matrix <- cbind(loading_matrix,Test = rownames(fa_4varimax_sorted))
```
```{r,echo=FALSE,collapse=TRUE}
loadings_melted <- reshape2::melt(loading_matrix, id="Test",
                                  measure=colnames(fa_4varimax_sorted),
                                  variable.name="Factor", value.name="Loading")
```
```{r,echo=FALSE,collapse=TRUE}
positions <- rev(rownames(fa_4varimax_sorted))

ggplot(loadings_melted, aes(Test, abs(Loading), fill=Loading)) + 
  facet_wrap(~ Factor, nrow=1) + #place the factors in separate facets
  geom_bar(stat="identity") + #make the bars
  coord_flip() + #flip the axes so the test names can be horizontal  
  #define the fill color gradient: blue=positive, red=negative
  scale_fill_gradient2(name = "Loading", 
                       high = "blue", mid = "white", low = "red", 
                       midpoint=0, guide=F) +
  scale_x_discrete(label = code_category(positions), limits = positions) +
  ggtitle("4 Factors - Varimax") +
  geom_hline(yintercept=0.3, size=0.7 ,col = 'red', linetype = "dotted") +
  xlab("Variables") +
  ylab("Loading Strength") + #improve y-axis label
  theme_bw(base_size=10)
```

```{r,echo=FALSE,collapse=TRUE}
fa_4quartimax_sorted <- fa.sort(fa_4quartimax$loadings) 
loading_matrix <- as.data.frame((matrix(fa_4quartimax_sorted, ncol = 4, nrow = 20, 
                         dimnames = list(NULL,colnames(fa_4quartimax_sorted)))))
loading_matrix <- cbind(loading_matrix,Test = rownames(fa_4quartimax_sorted))
```
```{r,echo=FALSE,collapse=TRUE}
loadings_melted <- reshape2::melt(loading_matrix, id="Test",
                                  measure=colnames(fa_4quartimax_sorted),
                                  variable.name="Factor", value.name="Loading")
```
```{r,echo=FALSE,collapse=TRUE}
positions <- rev(rownames(fa_4quartimax_sorted))

ggplot(loadings_melted, aes(Test, abs(Loading), fill=Loading)) + 
  facet_wrap(~ Factor, nrow=1) + #place the factors in separate facets
  geom_bar(stat="identity") + #make the bars
  coord_flip() + #flip the axes so the test names can be horizontal  
  #define the fill color gradient: blue=positive, red=negative
  scale_fill_gradient2(name = "Loading", 
                       high = "blue", mid = "white", low = "red", 
                       midpoint=0, guide=F) +
  scale_x_discrete(label = code_category(positions), limits = positions) +
  xlab("Variables") +
  geom_hline(yintercept=0.3,size=0.7 ,col = 'red', linetype = "dotted") +
  ggtitle("4 Factors - Quartimax") +
  ylab("Loading Strength") + #improve y-axis label
  theme_bw(base_size=10)
```
```{r,echo=FALSE,collapse=TRUE}
fa_4oblimin_sorted <- fa.sort(fa_4oblimin$loadings) 
loading_matrix <- as.data.frame((matrix(fa_4oblimin_sorted, ncol = 4, nrow = 20, 
                         dimnames = list(NULL,colnames(fa_4oblimin_sorted)))))
loading_matrix <- cbind(loading_matrix,Test = rownames(fa_4oblimin_sorted))
```
```{r,echo=FALSE,collapse=TRUE}
loadings_melted <- reshape2::melt(loading_matrix, id="Test",
                                  measure=colnames(fa_4oblimin_sorted),
                                  variable.name="Factor", value.name="Loading")
```
```{r,echo=FALSE,collapse=TRUE}
positions <- rev(rownames(fa_4oblimin_sorted))

ggplot(loadings_melted, aes(Test, abs(Loading), fill=Loading)) + 
  facet_wrap(~ Factor, nrow=1) + #place the factors in separate facets
  geom_bar(stat="identity") + #make the bars
  coord_flip() + #flip the axes so the test names can be horizontal  
  #define the fill color gradient: blue=positive, red=negative
  scale_fill_gradient2(name = "Loading", 
                       high = "blue", mid = "white", low = "red", 
                       midpoint=0, guide=F) +
  scale_x_discrete(label = code_category(positions), limits = positions) +
  xlab("Variables") +
  geom_hline(yintercept=0.3, size=0.7 ,col = 'red', linetype = "dotted") +
  ggtitle("4 Factors - Oblimin") +
  ylab("Loading Strength") + #improve y-axis label
  theme_bw(base_size=10)
```

#### 5 FACTORS
```{r}
fa_5varimax <- psych::fa(r = vitamin,
nfactors = 5,
rotate = "varimax",
scores = "regression",
SMC = T,
fm = "pa")

fa_5quartimax <- psych::fa(r = vitamin,
nfactors = 5,
rotate = "quartimax",
scores = "regression",
SMC = T,
fm = "pa")

fa_5oblimin <- psych::fa(r = vitamin,
nfactors = 5,
rotate = "oblimin",
scores = "regression",
SMC = T,
fm = "pa")

```
```{r}
fa.diagram(fa_5varimax)
fa.diagram(fa_5quartimax)
fa.diagram(fa_5oblimin)

```


```{r,echo=FALSE,collapse=TRUE}
fa_5varimax_sorted <- fa.sort(fa_5varimax$loadings) 
loading_matrix <- as.data.frame((matrix(fa_5varimax_sorted, ncol = 5, nrow = 20, 
                         dimnames = list(NULL,colnames(fa_5varimax_sorted)))))
loading_matrix <- cbind(loading_matrix,Test = rownames(fa_5varimax_sorted))
```
```{r,echo=FALSE,collapse=TRUE}
loadings_melted <- reshape2::melt(loading_matrix, id="Test",
                                  measure=colnames(fa_5varimax_sorted),
                                  variable.name="Factor", value.name="Loading")
```
```{r,echo=FALSE,collapse=TRUE}
positions <- rev(rownames(fa_5varimax_sorted))

ggplot(loadings_melted, aes(Test, abs(Loading), fill=Loading)) + 
  facet_wrap(~ Factor, nrow=1) + #place the factors in separate facets
  geom_bar(stat="identity") + #make the bars
  coord_flip() + #flip the axes so the test names can be horizontal  
  #define the fill color gradient: blue=positive, red=negative
  scale_fill_gradient2(name = "Loading", 
                       high = "blue", mid = "white", low = "red", 
                       midpoint=0, guide=F) +
  scale_x_discrete(label = code_category(positions), limits = positions) +
  xlab("Variables") +
  geom_hline(yintercept=0.3, size=0.7 ,col = 'red', linetype = "dotted") +
  ggtitle("5 Factors - Varimax") +
  ylab("Loading Strength") + #improve y-axis label
  theme_bw(base_size=10)
```
```{r,echo=FALSE,collapse=TRUE}
fa_5quartimax_sorted <- fa.sort(fa_5quartimax$loadings) 
loading_matrix <- as.data.frame((matrix(fa_5quartimax_sorted, ncol = 5, nrow = 20, 
                         dimnames = list(NULL,colnames(fa_5quartimax_sorted)))))
loading_matrix <- cbind(loading_matrix,Test = rownames(fa_5quartimax_sorted))
```
```{r,echo=FALSE,collapse=TRUE}
loadings_melted <- reshape2::melt(loading_matrix, id="Test",
                                  measure=colnames(fa_5quartimax_sorted),
                                  variable.name="Factor", value.name="Loading")
```
```{r,echo=FALSE,collapse=TRUE}
positions <- rev(rownames(fa_5quartimax_sorted))

ggplot(loadings_melted, aes(Test, abs(Loading), fill=Loading)) + 
  facet_wrap(~ Factor, nrow=1) + #place the factors in separate facets
  geom_bar(stat="identity") + #make the bars
  coord_flip() + #flip the axes so the test names can be horizontal  
  #define the fill color gradient: blue=positive, red=negative
  scale_fill_gradient2(name = "Loading", 
                       high = "blue", mid = "white", low = "red", 
                       midpoint=0, guide=F) +
  scale_x_discrete(label = code_category(positions), limits = positions) +
  xlab("Variables") +
  geom_hline(yintercept=0.3, size=0.7 ,col = 'red', linetype = "dotted") +
  ggtitle("5 Factors - Quartimax") +
  ylab("Loading Strength") + #improve y-axis label
  theme_bw(base_size=10)
```

```{r,echo=FALSE,collapse=TRUE}
fa_5oblimin_sorted <- fa.sort(fa_5oblimin$loadings) 
loading_matrix <- as.data.frame((matrix(fa_5oblimin_sorted, ncol = 5, nrow = 20, 
                         dimnames = list(NULL,colnames(fa_5oblimin_sorted)))))
loading_matrix <- cbind(loading_matrix,Test = rownames(fa_5oblimin_sorted))
```
```{r,echo=FALSE,collapse=TRUE}
loadings_melted <- reshape2::melt(loading_matrix, id="Test",
                                  measure=colnames(fa_5oblimin_sorted),
                                  variable.name="Factor", value.name="Loading")
```
```{r,echo=FALSE,collapse=TRUE}
positions <- rev(rownames(fa_5oblimin_sorted))

ggplot(loadings_melted, aes(Test, abs(Loading), fill=Loading)) + 
  facet_wrap(~ Factor, nrow=1) + #place the factors in separate facets
  geom_bar(stat="identity") + #make the bars
  coord_flip() + #flip the axes so the test names can be horizontal  
  #define the fill color gradient: blue=positive, red=negative
  scale_fill_gradient2(name = "Loading", 
                       high = "blue", mid = "white", low = "red", 
                       midpoint=0, guide=F) +
  scale_x_discrete(label = code_category(positions), limits = positions) +
  xlab("Variables") +
  geom_hline(yintercept=0.3, size=0.7 ,col = 'red', linetype = "dotted") +
  ggtitle("5 Factors - Oblimin") +
  ylab("Loading Strength") + #improve y-axis label
  theme_bw(base_size=10)
```

#### 6 FACTORS
```{r}
fa_6varimax <- psych::fa(r = vitamin,
nfactors = 6,
rotate = "varimax",
scores = "regression",
SMC = T,
fm = "pa")

fa_6quartimax <- psych::fa(r = vitamin,
nfactors = 6,
rotate = "quartimax",
scores = "regression",
SMC = T,
fm = "pa")

fa_6oblimin <- psych::fa(r = vitamin,
nfactors = 6,
rotate = "oblimin",
scores = "regression",
SMC = T,
fm = "pa")

```
```{r}
fa.diagram(fa_6varimax)
fa.diagram(fa_6quartimax)
fa.diagram(fa_6oblimin)

```


```{r,echo=FALSE,collapse=TRUE}
fa_6varimax_sorted <- fa.sort(fa_6varimax$loadings) 
loading_matrix <- as.data.frame((matrix(fa_6varimax_sorted, ncol = 6, nrow = 20, 
                         dimnames = list(NULL,colnames(fa_6varimax_sorted)))))
loading_matrix <- cbind(loading_matrix,Test = rownames(fa_6varimax_sorted))
```
```{r,echo=FALSE,collapse=TRUE}
loadings_melted <- reshape2::melt(loading_matrix, id="Test",
                                  measure=colnames(fa_6varimax_sorted),
                                  variable.name="Factor", value.name="Loading")
```
```{r,echo=FALSE,collapse=TRUE}
positions <- rev(rownames(fa_6varimax_sorted))

ggplot(loadings_melted, aes(Test, abs(Loading), fill=Loading)) + 
  facet_wrap(~ Factor, nrow=1) + #place the factors in separate facets
  geom_bar(stat="identity") + #make the bars
  coord_flip() + #flip the axes so the test names can be horizontal  
  #define the fill color gradient: blue=positive, red=negative
  scale_fill_gradient2(name = "Loading", 
                       high = "blue", mid = "white", low = "red", 
                       midpoint=0, guide=F) +
  scale_x_discrete(label = code_category(positions), limits = positions) +
  xlab("Variables") +
  geom_hline(yintercept=0.3, size=0.7 ,col = 'red', linetype = "dotted") +
  ggtitle("6 Factors - Varimax") +
  ylab("Loading Strength") + #improve y-axis label
  theme_bw(base_size=10)
```
```{r,echo=FALSE,collapse=TRUE}
fa_6quartimax_sorted <- fa.sort(fa_6quartimax$loadings) 
loading_matrix <- as.data.frame((matrix(fa_6quartimax_sorted, ncol = 6, nrow = 20, 
                         dimnames = list(NULL,colnames(fa_6quartimax_sorted)))))
loading_matrix <- cbind(loading_matrix,Test = rownames(fa_6quartimax_sorted))
```
```{r,echo=FALSE,collapse=TRUE}
loadings_melted <- reshape2::melt(loading_matrix, id="Test",
                                  measure=colnames(fa_6quartimax_sorted),
                                  variable.name="Factor", value.name="Loading")
```
```{r,echo=FALSE,collapse=TRUE}
positions <- rev(rownames(fa_6quartimax_sorted))

ggplot(loadings_melted, aes(Test, abs(Loading), fill=Loading)) + 
  facet_wrap(~ Factor, nrow=1) + #place the factors in separate facets
  geom_bar(stat="identity") + #make the bars
  coord_flip() + #flip the axes so the test names can be horizontal  
  #define the fill color gradient: blue=positive, red=negative
  scale_fill_gradient2(name = "Loading", 
                       high = "blue", mid = "white", low = "red", 
                       midpoint=0, guide=F) +
  scale_x_discrete(label = code_category(positions), limits = positions) +
  xlab("Variables") +
  geom_hline(yintercept=0.3, size=0.7 ,col = 'red', linetype = "dotted") +
  ggtitle("6 Factors - Quartimax") +
  ylab("Loading Strength") + #improve y-axis label
  theme_bw(base_size=10)
```

```{r,echo=FALSE,collapse=TRUE}
fa_6oblimin_sorted <- fa.sort(fa_6oblimin$loadings) 
loading_matrix <- as.data.frame((matrix(fa_6oblimin_sorted, ncol = 6, nrow = 20, 
                         dimnames = list(NULL,colnames(fa_6oblimin_sorted)))))
loading_matrix <- cbind(loading_matrix,Test = rownames(fa_6oblimin_sorted))
```
```{r,echo=FALSE,collapse=TRUE}
loadings_melted <- reshape2::melt(loading_matrix, id="Test",
                                  measure=colnames(fa_6oblimin_sorted),
                                  variable.name="Factor", value.name="Loading")
```
```{r,echo=FALSE,collapse=TRUE}
positions <- rev(rownames(fa_6oblimin_sorted))

ggplot(loadings_melted, aes(Test, abs(Loading), fill=Loading)) + 
  facet_wrap(~ Factor, nrow=1) + #place the factors in separate facets
  geom_bar(stat="identity") + #make the bars
  coord_flip() + #flip the axes so the test names can be horizontal  
  #define the fill color gradient: blue=positive, red=negative
  scale_fill_gradient2(name = "Loading", 
                       high = "blue", mid = "white", low = "red", 
                       midpoint=0, guide=F) +
  scale_x_discrete(label = code_category(positions), limits = positions) +
  xlab("Variables") +
  geom_hline(yintercept=0.3, size=0.7 ,col = 'red', linetype = "dotted") +
  ggtitle("6 Factors - Oblimin") +
  ylab("Loading Strength") + #improve y-axis label
  theme_bw(base_size=10)
```