---
title: "Stat 145 Assignment 6"
author:
  - name: "Marc Shervin Ignacio"
    affiliation: "2019-04690"
date: "`r format(Sys.time(), '%d %B %Y')`"
---
```{r, echo=FALSE}
show_table <- function(x,text=NULL){
  x %>%
  kbl(caption=text) %>%
  kable_classic(full_width = F, html_font = "Cambria")
}
```
```{r}
library("tidyverse")
library("readxl")
library(dplyr)
library("cluster")
library("fpc")
library("NbClust")
library("reshape2")
library(kableExtra)
```

```{r}
setwd("D:/Downloads")
audio_features <- read_xlsx("data.xlsx")
```
### First Objective
```{r}
filtered_audio_features <- audio_features %>% select(-c("...1", "type", "id", "uri", "track_href", "analysis_url", "track.name"  ))
```
```{r}
filtered_audio_features %>% summary()
```
```{r}
ggp2 <- ggplot(melt(filtered_audio_features), aes(x = value)) +    # Draw each column as density
  geom_density() + 
  facet_wrap(~ variable, scales = "free")
ggp2

```
### Second research objective
```{r}
continuous_features <- select(filtered_audio_features, -c("key", "mode", "time_signature"))
```
```{r}
continuous_features$popularity[198] = 0
```

```{r}
spotify_pc <- prcomp(x = continuous_features, scale.=T)
show_table(summary(spotify_pc)$importance, "Proportion of Total Variance retained per PC")
show_table(cbind(1:length(spotify_pc$sdev),spotify_pc$sdev),"Standard deviation of components")
show_table(spotify_pc$rotation, "PC Loadings")
```
```{r}
library(ggplot2)
ggplot(reshape2::melt(spotify_pc$rotation[,1:5]), aes(Var1, value, fill=value)) + 
  facet_wrap(~ Var2, nrow=1) + #place the factors in separate facets
  geom_bar(stat="identity") + #make the bars
  coord_flip() + #flip the axes so the test names can be horizontal  
  #define the fill color gradient: blue=positive, red=negative
  ggtitle("PCA_Spotify") +
    #scale_fill_gradient(low = "red", high = "green")+
   scale_fill_gradient2(name = "Scale", 
                        high = "blue", low = "red", 
                        midpoint=0) +
  xlab("Variable") +
  ylab("Loadings") + #improve y-axis label
  theme_bw(base_size=10)
```

```{r}
data_matrix <- spotify_pc$x[,1:5]
validation_stats <- NbClust::NbClust(data = data_matrix, diss = NULL, min.nc = 2, max.nc = 10, method = "ward.D")
```
```{r}
validation_stats$All.index %>%
  as_tibble(rownames = "no. of clusters")
```

```{r}
validation_stats$All.index %>%
  as_tibble(rownames = "no. of clusters")
```
```{r}
validation_stats$Best.nc %>%
  as_tibble(rownames = "Number_clusters")
```

```{r}
agnes_z_wards <- cluster::agnes(x = data_matrix,diss = FALSE, stand = T, method = "ward")

spotify_clusters <- audio_features %>%
                            mutate(
                              if_3_clusters = cutree(agnes_z_wards, k = 3),
                              if_4_clusters = cutree(agnes_z_wards, k = 4),
                              if_5_clusters = cutree(agnes_z_wards, k = 5),
                              if_6_clusters = cutree(agnes_z_wards, k = 6),
                              if_7_clusters = cutree(agnes_z_wards, k = 7),
                              if_8_clusters = cutree(agnes_z_wards, k = 8),
                              if_9_clusters = cutree(agnes_z_wards, k = 9),
                              if_10_clusters= cutree(agnes_z_wards, k = 10) 
                              )
```


```{r}
plot(agnes_z_wards)
```


```{r}
aggregate(scale(data[,c(2,3,4,5)]), competition_clusters[,7], FUN=mean)
```

```{r}
init_centers <- competition_clusters %>%
                  select(2,3,4,5,7) %>%
                  mutate_all(.funs = scale) %>%
                  group_by(if_4_clusters) %>%
                  summarise_all(.funs = mean) %>%
                  select(-if_4_clusters)
```
```{r}

cbind(cluster = c(1,2,3,4),init_centers)
```

```{r}
kmeans1 <- kmeans(x = scale(competition[-1]), centers = init_centers)
table(kmeans1$cluster)
```

```{r}
dist_euc_z2  <- daisy(competition[-1], metric = "euclidean", stand = T)
kmeans_stats <- fpc::cluster.stats(d = dist_euc_z2, clustering = kmeans1$cluster)
hclust_stats <- fpc::cluster.stats(d = dist_euc_z2, clustering = competition_clusters$if_4_clusters)
c("kmeans" = kmeans_stats$avg.silwidth, "hclust" = hclust_stats$avg.silwidth)
```

```{r}
c("kmeans" = kmeans_stats$ch, "hclust" = hclust_stats$ch)
```

```{r}
Final_clusters <- cbind(competition, cluster = kmeans1$cluster)
```


```{r}
competition[,-1] %>%
  mutate_all(.funs = scale) %>%
  mutate(cluster = kmeans1$cluster) %>%
  group_by(cluster) %>%
  summarise_all(.funs = mean) %>%
  reshape2::melt(id="cluster", variable.name="Factor", value.name="Scale") -> means_melted

```
```{r}
library(ggplot2)

ggplot(means_melted, aes(Factor, Scale, fill=Scale)) + 
  facet_wrap(~ cluster, nrow=1) + #place the factors in separate facets
  geom_bar(stat="identity") + #make the bars
  coord_flip() + #flip the axes so the test names can be horizontal  
  #define the fill color gradient: blue=positive, red=negative
  ggtitle("K = 4, Kmeans") +
    #scale_fill_gradient(low = "red", high = "green")+
   scale_fill_gradient2(name = "Scale", 
                        high = "blue", low = "red", 
                        midpoint=0) +
  xlab("Variables") +
  ylab("Means") + #improve y-axis label
  theme_bw(base_size=10)
```
```{r}
radiant.data::dtab(Final_clusters)
```

```{r}

# Libraries
library(mapsapi)
library(leaflet)

```
```{r}
getColor <- function(x){
  case_when(
    x == 1 ~ "yellow",
    x == 2 ~ "#90EE90",
    x == 3 ~ "red",
    x == 4 ~ "green"
  )
}

```
```{r}
load("point.RData")

palette = colorFactor(palette = "Set2", domain = point$location_type)

leaflet() %>% 
  addProviderTiles(provider = providers$CartoDB.Positron) %>%
  addCircleMarkers(data = point, color = getColor(Final_clusters$cluster),label = ~address_google) %>%
  setView(lng = 121.0550093, lat = 14.4770279, zoom = 12)
```


