---
title: "Final Paper Results"
author:
- name: Marc Shervin Ignacio
  affiliation: "2019-04690"
date: "`r format(Sys.time(), '%d %B %Y')`"
---
```{r, echo=FALSE}
show_table <- function(x,text=NULL){
  x %>%
  kbl(caption=text) %>%
  kable_classic(full_width = F, html_font = "Cambria")
}
```
```{r}
library("tidyverse")
library("readxl")
library(dplyr)
library("cluster")
library("fpc")
library("NbClust")
library("reshape2")
library(kableExtra)
```

```{r}
setwd("D:/Downloads")
audio_features <- read_xlsx("data.xlsx")
audio_features$duration_ms <- audio_features$duration_ms/60000
load("division.RData")
load("809000s.RData")
```
### First Objective
```{r}
groups <- as.data.frame(rbind(cbind(division[[1]]$id, 1),
cbind(t809000s[[1]], 2),
cbind(t809000s[[2]], 3),
cbind(t809000s[[3]], 4),
cbind(division[[3]], 5)))
colnames(groups) <- c("id", "group")
```

```{r}
first_research <- left_join(audio_features, groups, by = c("id" = "id")) %>% select(-c("...1", "type", "id", "uri", "track_href", "analysis_url", "track.name" , "popularity" ))
```

```{r}
filtered_audio_features <- audio_features %>% select(-c("...1", "type", "id", "uri", "track_href", "analysis_url", "track.name" , "popularity" ))
```

```{r}
melted_groups <- melt(first_research)
groupings <- list()
for(i in 1:5){
  groupings[[i]] <- melted_groups[melted_groups[,"group"] == i,]
}

ggp2 <- ggplot(groupings[[1]], aes(x = value)) +    # Draw each column as density
  geom_density() + 
  facet_wrap(~ variable, scales = "free")
ggp2
  
ggp2 <- ggplot(groupings[[2]], aes(x = value)) +    # Draw each column as density
  geom_density() + 
  facet_wrap(~ variable, scales = "free")
ggp2
  
ggp2 <- ggplot(groupings[[3]], aes(x = value)) +    # Draw each column as density
  geom_density() + 
  facet_wrap(~ variable, scales = "free")
ggp2
  

ggp2 <- ggplot(groupings[[4]], aes(x = value)) +    # Draw each column as density
  geom_density() + 
  facet_wrap(~ variable, scales = "free")
ggp2
  
ggp2 <- ggplot(groupings[[5]], aes(x = value)) +    # Draw each column as density
  geom_density() + 
  facet_wrap(~ variable, scales = "free")
ggp2
  

```

```{r}
groupings_sum <- list()
for(i in 1:5){
  groupings_sum[[i]] <- summary(first_research[first_research[,"group"] == i,])
}
groupings_sum
```
```{r}
vtable::st(first_research, group = "group", summ=c('min(x)', 'max(x)',
                'mean(x)',
                'median(x)',
                'sd(x)'))
```

### Second research objective
```{r}
continuous_features <- select(filtered_audio_features, -c("key", "mode", "time_signature"))
```
# ```{r}
# continuous_features$popularity[198] = 0
# ```

```{r}
spotify_pc <- prcomp(x = continuous_features, scale.=T)
show_table(summary(spotify_pc)$importance, "Proportion of Total Variance retained per PC")
show_table(cbind(1:length(spotify_pc$sdev),spotify_pc$sdev),"Standard deviation of components")
show_table(spotify_pc$rotation, "PC Loadings")
```
```{r}
library(factoextra)
fviz_pca_biplot(spotify_pc, geom = FALSE)
```

```{r}
library(ggplot2)
ggplot(reshape2::melt(spotify_pc$rotation[,1:5]), aes(Var1, value, fill=value)) + 
  facet_wrap(~ Var2, nrow=1) + #place the factors in separate facets
  geom_bar(stat="identity") + #make the bars
  coord_flip() + #flip the axes so the test names can be horizontal  
  #define the fill color gradient: blue=positive, red=negative
  ggtitle("PCA_Spotify") +
    #scale_fill_gradient(low = "red", high = "green")+
   scale_fill_gradient2(name = "Scale", 
                        high = "blue", low = "red", 
                        midpoint=0) +
  xlab("Variable") +
  ylab("Loadings") + #improve y-axis label
  theme_bw(base_size=10)
```


### Third Research Objective
```{r}
datamatrix <- spotify_pc$x[,1:5]
validation_stats <- NbClust::NbClust(data = datamatrix, diss = NULL, min.nc = 2, max.nc = 10, method = "ward.D")
```

```{r}
validation_stats$All.index %>%
  as_tibble(rownames = "no. of clusters") %>%
  show_table()
```

```{r}
validation_stats$All.index %>%
  as_tibble(rownames = "no. of clusters") %>%
  show_table()
```
```{r}
validation_stats$Best.nc %>%
  as_tibble(rownames = "Number_clusters") %>%
  show_table()
```

```{r}
agnes_z_wards <- cluster::agnes(x = datamatrix,diss = FALSE, stand = T, method = "ward")

spotify_clusters <- datamatrix %>%
                            as.data.frame() %>%
                            mutate(
                              if_3_clusters = cutree(agnes_z_wards, k = 3),
                              if_4_clusters = cutree(agnes_z_wards, k = 4),
                              if_5_clusters = cutree(agnes_z_wards, k = 5),
                              if_6_clusters = cutree(agnes_z_wards, k = 6),
                              if_7_clusters = cutree(agnes_z_wards, k = 7),
                              if_8_clusters = cutree(agnes_z_wards, k = 8),
                              if_9_clusters = cutree(agnes_z_wards, k = 9),
                              if_10_clusters= cutree(agnes_z_wards, k = 10) 
                              )
```


```{r}
table(cutree(agnes_z_wards, k = 5))
```


```{r}
plot(agnes_z_wards)
```



```{r}
init_centers <- spotify_clusters %>%
                  select(1:5,if_5_clusters) %>%
                  mutate_all(.funs = scale) %>%
                  group_by(if_5_clusters) %>%
                  summarise_all(.funs = mean) %>%
                  select(-if_5_clusters)
```

```{r}
cbind(cluster = c(1,2,3,4,5),init_centers) %>% show_table()
```


```{r}
kmeans1 <- kmeans(x = scale(datamatrix), centers = init_centers)
table(kmeans1$cluster)
```

```{r}
dist_euc_z2  <- daisy(datamatrix, metric = "euclidean", stand = T)
kmeans_stats <- fpc::cluster.stats(d = dist_euc_z2, clustering = kmeans1$cluster)
hclust_stats <- fpc::cluster.stats(d = dist_euc_z2, clustering = spotify_clusters$if_3_clusters)
c("kmeans" = kmeans_stats$avg.silwidth, "hclust" = hclust_stats$avg.silwidth)
```

```{r}
c("kmeans" = kmeans_stats$ch, "hclust" = hclust_stats$ch)
```

```{r}
Final_clusters <- cbind(datamatrix, cluster = kmeans1$cluster)
```


```{r}
Final_clusters %>%
                  as.data.frame() %>%
                  group_by(cluster) %>%
                  summarise_all(.funs = mean) %>%
                  reshape2::melt(id="cluster", variable.name="Factor", value.name="Scale") -> means_melted
```


```{r}
library(ggplot2)

ggplot(means_melted, aes(Factor, Scale, fill=Scale)) + 
  facet_wrap(~ cluster, nrow=1) + #place the factors in separate facets
  geom_bar(stat="identity") + #make the bars
  coord_flip() + #flip the axes so the test names can be horizontal  
  #define the fill color gradient: blue=positive, red=negative
  ggtitle("K = 5, Kmeans") +
    #scale_fill_gradient(low = "red", high = "green")+
   scale_fill_gradient2(name = "Scale", 
                        high = "blue", low = "red", 
                        midpoint=0) +
  scale_x_discrete(labels=c("Jazz Pop Quality", "Folk Pop Quality", "Upbeat Pop-Rock Quality", "Ballad Quality", "Rock Ballad Quality")) +
  xlab("Variables") +
  ylab("Means") + #improve y-axis label
  theme_bw(base_size=10)
```
