---
title: "Stat 145 Assignment 6"
author:
  - name: "Marc Shervin Ignacio"
    affiliation: "2019-04690"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  html_document:
    theme: lumen
    toc: yes
    toc_float: yes
    toc_depth: 4
    number_sections: no
    highlight: pygments
    fig_caption: yes
editor_options: 
  markdown: 
    wrap: 72
---
```{r}
library("tidyverse")
library("readxl")
library("cluster")
library("fpc")
library("NbClust")
```

```{r}
competition <- read_excel("Local Competitiveness Data.xlsx", sheet = "DATA")
data_matrix <- competition %>% select(-`PROVINCE / LGU`)
```

```{r}
validation_stats <- NbClust::NbClust(data = data_matrix, diss = NULL, min.nc = 3, max.nc = 10, method = "ward.D")
```
```{r}
validation_stats$All.index %>%
  as_tibble(rownames = "no. of clusters")
```

```{r}
validation_stats$All.index %>%
  as_tibble(rownames = "no. of clusters")
```
```{r}
validation_stats$Best.nc %>%
  as_tibble(rownames = "Number_clusters")
```

```{r}
agnes_z_wards <- cluster::agnes(x = data_matrix,diss = FALSE, stand = T, method = "ward")

competition_clusters <- competition %>%
                            mutate(
                              if_3_clusters = cutree(agnes_z_wards, k = 3),
                              if_4_clusters = cutree(agnes_z_wards, k = 4),
                              if_5_clusters = cutree(agnes_z_wards, k = 5),
                              if_6_clusters = cutree(agnes_z_wards, k = 6),
                              if_7_clusters = cutree(agnes_z_wards, k = 7),
                              if_8_clusters = cutree(agnes_z_wards, k = 8),
                              if_9_clusters = cutree(agnes_z_wards, k = 9),
                              if_10_clusters= cutree(agnes_z_wards, k = 10) 
                              )
```

```{r}
competition_clusters
```

```{r}
plot(agnes_z_wards)
```

```{r}
table(cutree(agnes_z_wards, k = 4))
table(cutree(agnes_z_wards, k = 5))
```
```{r}
cluster_5 <- competition_clusters[,c(1,8)] 
cluster_5_1_2 <- filter(cluster_5, if_5_clusters == 1 | if_5_clusters == 2)
cluster_4_1 <- filter(competition_clusters, if_4_clusters == 1)
```
```{r}
inner_join(competition,cluster_5_1_2)
```

```{r}
inner_join(cluster_4_1,cluster_5_1_2)
```


```{r}
competition_clusters
```

```{r}
init_centers <- competition_clusters %>%
                  select(2,3,4,5,7) %>%
                  mutate_all(.funs = scale) %>%
                  group_by(if_4_clusters) %>%
                  summarise_all(.funs = mean) %>%
                  select(-if_4_clusters)
```
```{r}
kmeans1 <- kmeans(x = scale(competition[-1]), centers = init_centers)
table(kmeans1$cluster)
```

```{r}
dist_euc_z2  <- daisy(competition[-1], metric = "euclidean", stand = T)
kmeans_stats <- fpc::cluster.stats(d = dist_euc_z2, clustering = kmeans1$cluster)
hclust_stats <- fpc::cluster.stats(d = dist_euc_z2, clustering = competition_clusters$if_4_clusters)
c("kmeans" = kmeans_stats$avg.silwidth, "hclust" = hclust_stats$avg.silwidth)
```

```{r}
c("kmeans" = kmeans_stats$ch, "hclust" = hclust_stats$ch)
```

### 3 
```{r}
Final_clusters <- cbind(competition, cluster = kmeans1$cluster)
Final_clusters
```
```{r}
final_centers <- Final_clusters[,-1] %>%
                  group_by(cluster) %>%
                  summarise_all(.funs = mean)
final_centers
```
```{r}
means_melted <- reshape2::melt(final_centers, id="cluster",
                                  variable.name="Factor", value.name="Mean")
means_melted
```

```{r}
library(ggplot2)

ggplot(means_melted, aes(Factor, Mean)) + 
  facet_wrap(~ cluster, nrow=1) + #place the factors in separate facets
  geom_bar(stat="identity") + #make the bars
  coord_flip() + #flip the axes so the test names can be horizontal  
  #define the fill color gradient: blue=positive, red=negative
  scale_fill_gradient2(name = "Loading", 
                       high = "blue", mid = "white", low = "red", 
                       midpoint=0, guide=F) +
  ggtitle("K = 4, Kmeans") +
  xlab("Variables") +
  ylab("Means") + #improve y-axis label
  theme_bw(base_size=10)
```
```{r}
competition[,-1] %>%
  mutate_all(.funs = scale) %>%
  mutate(cluster = kmeans1$cluster) %>%
  group_by(cluster) %>%
  summarise_all(.funs = mean) %>%
  reshape2::melt(id="cluster", variable.name="Factor", value.name="Scale") -> means_melted

```
```{r}
library(ggplot2)

ggplot(means_melted, aes(Factor, Scale, fill=Scale)) + 
  facet_wrap(~ cluster, nrow=1) + #place the factors in separate facets
  geom_bar(stat="identity") + #make the bars
  coord_flip() + #flip the axes so the test names can be horizontal  
  #define the fill color gradient: blue=positive, red=negative
  ggtitle("K = 4, Kmeans") +
  scale_fill_gradient2(name = "Scale", 
                       high = "blue", low = "red", 
                       midpoint=0, guide="none") +
  xlab("Variables") +
  ylab("Means") + #improve y-axis label
  theme_bw(base_size=10)
```

